package UserService.Enums;

public enum Permission {

	VIEW_BOOKS,
    ADD_BOOK,
    EDIT_BOOK,
    DELETE_BOOK,
    CHECKOUT_BOOK,
    RETURN_BOOK,
    RATE_BOOK,
    RESERVE_BOOK,
    VIEW_PROFILE,
    VIEW_BORROWING_HISTORY,
    MANAGE_USERS,
    ASSIGN_ROLES,
    VIEW_USER_HISTORY,
    CONFIGURE_SYSTEM,
    GENERATE_REPORTS,
    SEND_NOTIFICATIONS
}
